### ISSUE TITLE
File and Directory to monitor default settings cause crash

### ISSUE THREAD

**Issue by ceramicskate0** [ceramicskate0/SWELF#124]
ALERT: SWELF MAIN UNSALVAGEABLE ERROR: CREATE_NEW_Files_And_Dirs() check IO restrictions on machine for app.   Thread was being aborted.    at 
The default configs for file and directory to monitor, while commented, are causing thread to crash app. 

ERROR BELOW:
Microsoft.Win32.Win32Native.GetFileAttributesEx(String name, Int32 fileInfoLevel, WIN32_FILE_ATTRIBUTE_DATA& lpFileInformation)
   at System.IO.File.FillAttributeInfo(String path, WIN32_FILE_ATTRIBUTE_DATA& data, Boolean tryagain, Boolean returnErrorOnNotFound)
   at System.IO.Directory.InternalExists(String path, Int32& lastError)
   at System.IO.Directory.InternalExistsHelper(String path, Boolean checkHost)
   at System.IO.Directory.Exists(String path)
   at SWELF.File_Operation.CREATE_NEW_Files_And_Dirs(String Dir, String FileName, String FileData, Boolean Overwrite)

**Comment by ceramicskate0** [comment]
once the contents of the files are removed the app works as expected (previous errors prior to this one included)
